spring.application.name=backend

# Conexión persistente a PostgreSQL Supabase (Direct/Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.fghzrhgtdlvkzqidpvgx
spring.datasource.password=TU_PASSWORD_DE_SUPABASE
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}